name: chat_screen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  file_picker: ^6.2.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.2.0
  flutter_pdfview: ^1.3.2
  get: ^4.6.6
  http: ^1.2.0
  image_picker: ^1.0.7
  open_file: ^3.3.2
  path_provider: ^2.1.2
  receive_sharing_intent: ^1.6.7
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
